### ISSUE TITLE
Unreachable Flameblade?

### ISSUE THREAD

**Issue by yoosefi** [MrCheeze/botw-object-map#12]
The object map says there's a Flameblade (`Weapon_Sword_033`) sitting out on the plateau by itself.

![image](https://user-images.githubusercontent.com/2010434/69427815-c6773780-0ce4-11ea-81ff-009630425db1.png)

But there's nothing there. I confirmed this with unresponsive radar, wandering around on top of the plateau near that marker, and trying to get "underneath" the plateau (couldn't find a way). Can you find what the Z-axis is for that item? Is it out of bounds? If so please remove it from the map, as it cannot be obtained and shouldn't be considered "in-game".

Thanks!

**Comment by MrCheeze** [comment]
1) The point of the map is to accurately show the actual game data, if there *is* an unobtainable weapon then its discovery is in itself a successful use of the map.
2) It probably appears during the Trial of the Sword...

**Comment by yoosefi** [comment]
Wow, hadn't thought of that. Thanks!
