### ISSUE TITLE
Map not working Offline

### ISSUE THREAD

**Issue by Less-cell** [MrCheeze/botw-object-map#13]
i downloaded the object map and when i open the index html the page doesn' show any of the presets or any of the markers the only thing i can interact with is the map (i can move it and i can zoom in and out). 
![Breath of the Wild Object Map - Google Chrome 04_01_2020 00_34_07](https://user-images.githubusercontent.com/59490747/71755273-21767f80-2e8a-11ea-9dab-5f5475f1b823.png)

**Comment by MrCheeze** [comment]
Are you on chrome? If so, the --allow-file-access-from-files launch parameter might help.

**Comment by Less-cell** [comment]
Ok, it's now working, Thank you
