### ISSUE TITLE
Smotherwing Butterflies are not present in the object map

### ISSUE THREAD

**Issue by benlk** [MrCheeze/botw-object-map#14]
The map lists the following forms of butterfly:

- Winterwing Butterfly — `Animal_Insect_N`
- Summerwing Butterfly — `Animal_Insect_Q`
- Thunderwing Butterfly — `Animal_Insect_R`
- `Butterfly`

None of these are the Smotherwing Butterfly.

> Note that many objects are dynamically generated and are not included in this data.

If this is the case for Smotherwings, then please mark this issue as resolved. I'm filing this issue just in case Smotherwings are not dynamically generated, in case they were missed during an import of data from the game.

**Comment by MrCheeze** [comment]
Yep, whatever's included in the map is whatever data is available for individually placed actors. Smotherwings must be regional rather than explicitly placed.

**Comment by benlk** [comment]
Good to know; thankee!
