### ISSUE TITLE
Add approximite Travelling Saleman Solutions

### ISSUE THREAD

**Issue by CeruleanSky** [MrCheeze/botw-object-map#6]
I added a suggestion for a high speed solution for TSP here https://github.com/MrCheeze/botw-waypoint-map/issues/1 that I used myself. 

It might be nice to put it on the webserver map since it shouldn't require too much resources if your webserver supports python.  Though I'd change it to rendering the path via  javascript since image generation is expensive.  Also there are webpython/assembly ways of porting the code to run in the javascript vm if you didn't want to run on the webserver at all.

**Comment by MrCheeze** [comment]
Definitely some cool stuff you have there, but there are a few reasons not to integrate it - for one, I don't actually have a webserver, I'm just serving [static](https://mrcheeze.github.io/botw-object-map/) [files](https://mrcheeze.github.io/botw-waypoint-map/) here, meaning I'd have to reimplement it in JS. Furthermore it would be a bit of a feature bloat anyway. I do like what you've done though.
