### ISSUE TITLE
Missing item Stealthfin Trout

### ISSUE THREAD

**Issue by orcutt989** [MrCheeze/botw-object-map#9]
![image](https://user-images.githubusercontent.com/5608027/36510325-9fe27ce8-1730-11e8-9b3c-1b82f1af2915.png)
![image](https://user-images.githubusercontent.com/5608027/36510367-c20073ca-1730-11e8-8f06-0cc32ebc0d91.png)

http://www.ign.com/wikis/the-legend-of-zelda-breath-of-the-wild/Stealthfin_Trout

**Comment by MrCheeze** [comment]
apparently, none are individually placed on the map.
